[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
numFailures = 3

[variables]
NIXPACKS_NODE_VERSION = "18.19.0" 